target-version = "py39"
line-length = 88
output-format = "concise"

[lint]
select = ["B", "C", "E", "F", "W", "I"]
ignore = [
    "E501",  # don't enforce for comments and docstrings
    "B017",  # required for tests
    "B027",  # required for optional _tell method
    "B028",
    "B904",
    "B905",
]
isort.split-on-trailing-comma = false
isort.lines-after-imports = 2

[lint.mccabe]
max-complexity = 18
