name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11' ]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install Dependencies
        run: uv pip install -r requirements.txt --system

      - name: Run domain-only test
        run: |
          export ADD_DUMMY_TYPES=True
          uvicorn --app-dir=app app:app > dev/null & sleep 10
          pytest
          kill %1